[package]
name = "yukorust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web="4.0"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "2.2", features = ["postgres"]}